name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: build
      env:
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
        RUNTIME_TAG: ${GITHUB_REF}
      run: |
        docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
        echo 'Running build...'
        
        make build_base_x86_64 TAG=$RUNTIME_TAG
        make build_testing_x86_64 TAG=$RUNTIME_TAG
        make build_runtime_x86_64 TAG=$RUNTIME_TAG
