name: deploy_arm64

on:
    push:
        branches:
            - master

jobs:
    deploy_arm_64:
        runs-on: ubuntu-18.04
        steps:
        - name: git checkout
          uses: actions/checkout@v2
        - name: install dependencies
          run: |
            sudo apt-get update
            sudo apt-get install -y qemu binfmt-support qemu-user-static
        - name: build and deploy
          env:
                DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
                DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
          run: |
                docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
                echo 'Hello World!'
                
                make build_dependencies_arm64 TAG=${GITHUB_SHA} \
                                  FROM_TAG=latest \
                                  CACHE_TAG=latest
                make build_arm64 TAG=${GITHUB_SHA} \
                                  BUILD_TYPE=runtime \
                                  CACHE_TAG=latest

                docker tag martindeegan/acrobat:${GITHUB_SHA}_dependencies_arm64 martindeegan/acrobat:latest_dependencies_arm64
                docker tag martindeegan/acrobat:${GITHUB_SHA}_runtime_arm64 martindeegan/acrobat:latest_runtime_arm64
                docker tag martindeegan/acrobat:${GITHUB_SHA}_runtime_arm64 martindeegan/acrobat:latest

                make push_arm64 TAG=${GITHUB_SHA} PUSH_TYPE=dependencies
                make push_arm64 TAG=latest PUSH_TYPE=dependencies
                make push_arm64 TAG=${GITHUB_SHA} PUSH_TYPE=runtime
                make push_arm64 TAG=latest PUSH_TYPE=runtime
                docker push martindeegan/acrobat:latest

